[project]
name = "hollyddl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.0",
    "bs4>=0.0.2",
    "flask>=3.1.2",
    "pycryptodome>=3.23.0",
    "requests>=2.32.5",
]
